# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d42eba137f83be6c89f8bce359123985ed0dc8b122d10546858798c0c6af272d206b6711405f35a5a8bba2c0469579862f86be0894ebc42b6ea2909d0e382535

test:
  secret_key_base: 6934599ce6ee4fa1a1be663440b11ddbe833f0ae9ac55c0b7549d8d7d8a25ca94f7737e3551417d8a50f8e998bb3bd0f3f0fdc2ca7206ac74c742b1edcc65c77

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
